added new changes

diff --git a/.github/workflows/tf-plan-apply.yml b/.github/workflows/tf-plan-apply.yml
--- a/.github/workflows/tf-plan-apply.yml
+++ b/.github/workflows/tf-plan-apply.yml
@@ -218,6 +218,77 @@ jobs:
       #     echo "${delimiter}" >> $GITHUB_OUTPUT
       #   working-directory: ${{ env.WORKING_DIR }}
 
+      # - name: Create Terraform Summary Output
+      #   id: tf-plan-string
+      #   run: |
+      #     set +e
+      #     PLAN_PATH=tfplan
+
+      #     if [ ! -f "$PLAN_PATH" ]; then
+      #       echo "summary<<EOF" >> $GITHUB_OUTPUT
+      #       echo "⚠️ tfplan file is missing. Skipping summary." >> $GITHUB_OUTPUT
+      #       echo "EOF" >> $GITHUB_OUTPUT
+      #       exit 0
+      #     fi
+
+      #     terraform show -no-color "$PLAN_PATH" > tf_output.txt 2>/dev/null
+      #     if [ $? -ne 0 ]; then
+      #       echo "summary<<EOF" >> $GITHUB_OUTPUT
+      #       echo "⚠️ tfplan exists but could not be parsed." >> $GITHUB_OUTPUT
+      #       echo "EOF" >> $GITHUB_OUTPUT
+      #       exit 0
+      #     fi
+
+      #     CREATE_COUNT=$(grep -cE '^\s*#.*will be created' tf_output.txt || true)
+      #     UPDATE_COUNT=$(grep -cE '^\s*#.*will be (updated in-place|changed)' tf_output.txt || true)
+      #     DESTROY_COUNT=$(grep -cE '^\s*#.*will be destroyed' tf_output.txt || true)
+
+      #     delimiter="$(openssl rand -hex 8)"
+      #     echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
+
+      #     echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
+      #     echo "" >> $GITHUB_OUTPUT
+      #     echo "**Summary:** \`Plan: ${CREATE_COUNT} to add, ${UPDATE_COUNT} to change, ${DESTROY_COUNT} to destroy.\`" >> $GITHUB_OUTPUT
+      #     echo "" >> $GITHUB_OUTPUT
+
+      #     # Create
+      #     echo "<details open><summary>🟢 Create ${CREATE_COUNT}</summary>" >> $GITHUB_OUTPUT
+      #     echo "" >> $GITHUB_OUTPUT
+      #     echo '```diff' >> $GITHUB_OUTPUT
+      #     grep -A20 -E '^\s*#.*will be created' tf_output.txt || echo "No resources to create." >> $GITHUB_OUTPUT
+      #     echo '```' >> $GITHUB_OUTPUT
+      #     echo "</details>" >> $GITHUB_OUTPUT
+      #     echo "" >> $GITHUB_OUTPUT
+
+      #     # Update
+      #     echo "<details><summary>🟡 Update ${UPDATE_COUNT}</summary>" >> $GITHUB_OUTPUT
+      #     echo "" >> $GITHUB_OUTPUT
+      #     echo '```diff' >> $GITHUB_OUTPUT
+      #     grep -A20 -E '^\s*#.*will be (updated in-place|changed)' tf_output.txt || echo "No resources to update." >> $GITHUB_OUTPUT
+      #     echo '```' >> $GITHUB_OUTPUT
+      #     echo "</details>" >> $GITHUB_OUTPUT
+      #     echo "" >> $GITHUB_OUTPUT
+
+      #     # Destroy
+      #     echo "<details><summary>🔴 Destroy ${DESTROY_COUNT}</summary>" >> $GITHUB_OUTPUT
+      #     echo "" >> $GITHUB_OUTPUT
+      #     echo '```diff' >> $GITHUB_OUTPUT
+      #     grep -A20 -E '^\s*#.*will be destroyed' tf_output.txt || echo "No resources to destroy." >> $GITHUB_OUTPUT
+      #     echo '```' >> $GITHUB_OUTPUT
+      #     echo "</details>" >> $GITHUB_OUTPUT
+      #     echo "" >> $GITHUB_OUTPUT
+
+      #     # Full plan
+      #     echo "<details><summary>📜 Full Terraform Plan</summary>" >> $GITHUB_OUTPUT
+      #     echo "" >> $GITHUB_OUTPUT
+      #     echo '```diff' >> $GITHUB_OUTPUT
+      #     cat tf_output.txt >> $GITHUB_OUTPUT
+      #     echo '```' >> $GITHUB_OUTPUT
+      #     echo "</details>" >> $GITHUB_OUTPUT
+
+      #     echo "${delimiter}" >> $GITHUB_OUTPUT
+      #   working-directory: ${{ env.WORKING_DIR }}
+
       - name: Create Terraform Summary Output
         id: tf-plan-string
         run: |
@@ -246,45 +317,30 @@ jobs:
           delimiter="$(openssl rand -hex 8)"
           echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
 
-          echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
-          echo "" >> $GITHUB_OUTPUT
-          echo "**Summary:** \`Plan: ${CREATE_COUNT} to add, ${UPDATE_COUNT} to change, ${DESTROY_COUNT} to destroy.\`" >> $GITHUB_OUTPUT
-          echo "" >> $GITHUB_OUTPUT
+          echo "<h2>Terraform Plan Output</h2>" >> $GITHUB_OUTPUT
 
-          # Create
-          echo "<details open><summary>🟢 Create ${CREATE_COUNT}</summary>" >> $GITHUB_OUTPUT
-          echo "" >> $GITHUB_OUTPUT
-          echo '```diff' >> $GITHUB_OUTPUT
-          grep -A20 -E '^\s*#.*will be created' tf_output.txt || echo "No resources to create." >> $GITHUB_OUTPUT
-          echo '```' >> $GITHUB_OUTPUT
-          echo "</details>" >> $GITHUB_OUTPUT
-          echo "" >> $GITHUB_OUTPUT
+          echo "<strong>Summary:</strong>" >> $GITHUB_OUTPUT
+          echo "<ul>" >> $GITHUB_OUTPUT
+          echo "<li><strong style='color:green;'>🟢 Create:</strong> ${CREATE_COUNT}</li>" >> $GITHUB_OUTPUT
+          echo "<li><strong style='color:orange;'>🟡 Update:</strong> ${UPDATE_COUNT}</li>" >> $GITHUB_OUTPUT
+          echo "<li><strong style='color:red;'>🔴 Destroy:</strong> ${DESTROY_COUNT}</li>" >> $GITHUB_OUTPUT
+          echo "</ul><br>" >> $GITHUB_OUTPUT
 
-          # Update
-          echo "<details><summary>🟡 Update ${UPDATE_COUNT}</summary>" >> $GITHUB_OUTPUT
-          echo "" >> $GITHUB_OUTPUT
-          echo '```diff' >> $GITHUB_OUTPUT
-          grep -A20 -E '^\s*#.*will be (updated in-place|changed)' tf_output.txt || echo "No resources to update." >> $GITHUB_OUTPUT
-          echo '```' >> $GITHUB_OUTPUT
-          echo "</details>" >> $GITHUB_OUTPUT
-          echo "" >> $GITHUB_OUTPUT
+          echo "<details open><summary>🟢 <strong>Create ${CREATE_COUNT}</strong></summary><pre>" >> $GITHUB_OUTPUT
+          grep -E '^\s*#.*will be created' tf_output.txt || echo "No resources to create." >> $GITHUB_OUTPUT
+          echo "</pre></details><br>" >> $GITHUB_OUTPUT
 
-          # Destroy
-          echo "<details><summary>🔴 Destroy ${DESTROY_COUNT}</summary>" >> $GITHUB_OUTPUT
-          echo "" >> $GITHUB_OUTPUT
-          echo '```diff' >> $GITHUB_OUTPUT
-          grep -A20 -E '^\s*#.*will be destroyed' tf_output.txt || echo "No resources to destroy." >> $GITHUB_OUTPUT
-          echo '```' >> $GITHUB_OUTPUT
-          echo "</details>" >> $GITHUB_OUTPUT
-          echo "" >> $GITHUB_OUTPUT
+          echo "<details><summary>🟡 <strong>Update ${UPDATE_COUNT}</strong></summary><pre>" >> $GITHUB_OUTPUT
+          grep -E '^\s*#.*will be (updated in-place|changed)' tf_output.txt || echo "No resources to update." >> $GITHUB_OUTPUT
+          echo "</pre></details><br>" >> $GITHUB_OUTPUT
 
-          # Full plan
-          echo "<details><summary>📜 Full Terraform Plan</summary>" >> $GITHUB_OUTPUT
-          echo "" >> $GITHUB_OUTPUT
-          echo '```diff' >> $GITHUB_OUTPUT
+          echo "<details><summary>🔴 <strong>Destroy ${DESTROY_COUNT}</strong></summary><pre>" >> $GITHUB_OUTPUT
+          grep -E '^\s*#.*will be destroyed' tf_output.txt || echo "No resources to destroy." >> $GITHUB_OUTPUT
+          echo "</pre></details><br>" >> $GITHUB_OUTPUT
+
+          echo "<details><summary>📜 <strong>Full Terraform Plan</strong></summary><pre>" >> $GITHUB_OUTPUT
           cat tf_output.txt >> $GITHUB_OUTPUT
-          echo '```' >> $GITHUB_OUTPUT
-          echo "</details>" >> $GITHUB_OUTPUT
+          echo "</pre></details>" >> $GITHUB_OUTPUT
 
           echo "${delimiter}" >> $GITHUB_OUTPUT
         working-directory: ${{ env.WORKING_DIR }}
