edit plan format

diff --git a/.github/workflows/tf-plan-apply.yml b/.github/workflows/tf-plan-apply.yml
--- a/.github/workflows/tf-plan-apply.yml
+++ b/.github/workflows/tf-plan-apply.yml
@@ -91,13 +91,15 @@ jobs:
       - name: Terraform Plan
         id: tf-plan
         run: |
+          mkdir -p "${{ env.WORKING_DIR }}"
           export exitcode=0
-          terraform plan -detailed-exitcode -no-color -out ${{ env.WORKING_DIR }}/tfplan || export exitcode=$?
+          terraform plan -detailed-exitcode -no-color -out "${{ env.WORKING_DIR }}/tfplan" || export exitcode=$?
           echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+
           if [ $exitcode -eq 1 ]; then
-            echo Terraform Plan Failed!
+            echo "Terraform Plan Failed!"
             exit 1
-          else 
+          else
             exit 0
           fi
         working-directory: ${{ env.WORKING_DIR }}
